s = set()
n1 = input("Enter Number 1:")
s.add(int(n1))
n2 = input("Enter Number 2:")
s.add(int(n2))
n3 = input("Enter Number 3:")
s.add(int(n3))
n4 = input("Enter Number 4:")
s.add(int(n4))
n5 = input("Enter Number 5:")
s.add(int(n5))
n6 = input("Enter Number 6:")
s.add(int(n6))
n7 = input("Enter Number 7:")
s.add(int(n7))
n8 = input("Enter Number 8:")
s.add(int(n8))

print(s)